### ISSUE TITLE
TypeError: Cannot read property 'encrypted' of undefined

### ISSUE THREAD

**Issue by marcobarbosa** [nuxt-contrib/is-https#2]
`at isHTTPS (/app/node_modules/is-https/index.js:3:46)`

Testing this with `nuxt.js` and heroku staging. Using node >=8.9.1.

Shouldn't we test that we a `req.connection` here first?
```
  // Test using req.connection.encrypted
  const encrypted = isEmpty(req.connection.encrypted)...
```

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/is-https/issues/c2">#c2</a>)</em></sub></div>

**Comment by seenickcode** [comment]
@marcorbarbosa, was there any resolution to this? I am getting this in Nuxt when using Nuxt's proxy.

**Comment by marcobarbosa** [comment]
@seenickcode Sorry, but I don't remember what we did :/

**Comment by pi0** [comment]
Hi @seenickcode. Are you able to make a small reproduction repository?
